<?xml version="1.0" encoding="utf-8"?>
<applicationModel>
  <name>Application Model</name>
  <className>ApplicationModel</className>
  <objects>
    <object technology="WPF" type="Button">
      <name>test1</name>
      <codeName>Test1</codeName>
      <identification>
        <properties>
          <property name="Name" type="string">Button</property>
        </properties>
      </identification>
    </object>
  </objects>
</applicationModel>